source 'https://rubygems.org'

ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use HAML for markup
gem "haml", "~> 4.0.4"

# Pretty fonts
gem "font-awesome-sass-rails", "~> 3.0.0"

# Javascript date-picker
gem "bootstrap-datepicker-rails", "~> 1.1.0"

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use YUI as compressor for CSS assets
gem 'yui-compressor'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# Database
gem "pg", "~> 0.15"

# Enum-like attribute
gem "enumerize", "~> 0.6.1"

# Strip whitespace and convert "" -> nil on model validation
gem "strip_attributes", "~> 1.4"

# SASS version of Bootstrap
gem "bootstrap-sass", "~> 2.2.2.0"

gem "thin", "> 1.5.1"

gem "devise"

gem "rails_admin"

group :production do
  gem 'rails_12factor'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
